### ISSUE TITLE
/e books

### ISSUE THREAD

**Issue by Yavi0829** [JoeltheBrave/skyblock#14]
when an /e book fails when you add it to the item, its supposed to eat the book AND item (per noah). It currently only eats one item (from what I've experienced, and asked other players).

**Comment by thinkier** [comment]
I had an oxygenate book and diamond helmet both eaten, so this is weird...

**Comment by Yavi0829** [comment]
it seems to be sporadic. For the first like...5 or so times I used a book and it failed it only ate the book. Recently I used one, it ate the tool, not the book. I asked other players, they experienced the same thing, and others said it ate both. -shrug-

**Comment by JoeltheBrave** [comment]
There is a chance of items being eaten
