### ISSUE TITLE
[REQUEST] End Island

### ISSUE THREAD

**Issue by Yavi0829** [JoeltheBrave/skyblock#18]
So we get nether island at prestige I. I don't know what prestige, maybe III just to make it more varied or even IV, but I would love love LOVE an end island :D

**Comment by JoeltheBrave** [comment]
I would also like this but is a restriction to the skyblock plugin, I know it has been asked for and the developer is working on it. When it is released it will be implemented

**Comment by Yavi0829** [comment]
oh, awesome thanks
