### ISSUE TITLE
[SUGGESTION/REQUEST]

### ISSUE THREAD

**Issue by Yavi0829** [JoeltheBrave/skyblock#19]
Prestige doesnt give a ton of rewards rn outside of gen (they are awesome), I was thinking maybe we could possibly get more (even if their small) island expansions with the prestiges

**Comment by JoeltheBrave** [comment]
Unfortunately you cant make islands any bigger then 200x200 because it will overlap the other islands

**Comment by Yavi0829** [comment]
darn
