### ISSUE TITLE
"Floor Level" Lag

### ISSUE THREAD

**Issue by Yavi0829** [JoeltheBrave/skyblock#20]
not sure how to explain this where it'll make sense, and I dont know if it's only a "me" issue. I don't think it is since I very rarely (unless its server side) experience lag. When I place/remove blocks that are my floor level (I built on top of the bedrock for my floor) it lags intensely, I mean so much so that sometimes I crash.

**Comment by Monkeyboilol** [comment]
If there's lots of stuff going on underneath the floor layer, like a cactus farm, you can get massive lag spikes from simply removing/placing blocks that let you look at it. Not much to be done, it's just Minecraft.
