### ISSUE TITLE
Like signs

### ISSUE THREAD

**Issue by Yavi0829** [JoeltheBrave/skyblock#22]
![2018-05-08 3](https://user-images.githubusercontent.com/39056416/39784818-cf263cfe-52e7-11e8-9bbb-e0d406753e8b.png)

I had 8 island likes. AJC2 liked me island, went down to 0. Jake liked, went up to 10. Then it dropped back down to 7 again tho no one was unliking. (there def werent 7 people there all unliking at once lol) I think like signs are glitched

**Comment by Coltify** [comment]
Fixed waiting on Dhuine to upload new version of that plugin.
