### ISSUE TITLE
Daily bonus GUI interrupting afk sessions

### ISSUE THREAD

**Issue by thinkier** [JoeltheBrave/skyblock#5]
Currently, the daily bonus GUI pops up right on top the game without ways to disable it, my suggestion is to:

- [x] Either make it claim by command or simply send a few lines of chat instead of deactivating auto-miners. 
- [x] It needs a bit of a change as the daily bonus is not very useful or rewarding to late-game players as $20k is a trivial amount at this stage.

**Comment by JoeltheBrave** [comment]
Enabled auto claim and set day 6 reward to 100k
