### ISSUE TITLE
Seller Minions Won't Sell Feathers +1 more

### ISSUE THREAD

**Issue by AJC2MC** [JoeltheBrave/skyblock#7]
The seller minions are supposed to be able to sell anything (that's what I heard) but mine will not sell feathers. 
They also eat 1 food per second, which is ridiculous considering chicken and cow spawners are super rare. The seller minion fixes the hopper limit issue, but it breaks when the minion's food farm can't keep up.

**Comment by JoeltheBrave** [comment]
Added feathers to sell
